language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy: 
  provider: pages
  edge: true
  cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master