language: node_js
cache:
  directories:
    ~/.npm
    node_js
    - "12"
  git:
    depth: 3
  script:
    - yarn build
  deploy:
    provider: pages
    edge: true
    skip-cleanup: true
    keep-history: true
    target_branch: gh-pages
    github-token: $GITHUB_TOKEN
    local-dir: dist/
    commit_message: "Deploy Release"
    on:
      branch: main